//PART OF THE HTML DOCUMENT TO SAVE
//TO CREATE FILE TO SAVE
function saveDynamicDataToFile() {
	var pageTitle = document.querySelector('title');
	var template;
	var allLinks = document.querySelectorAll('link');
	for (i = allLinks.length - 1; i > 0; i--) {
		linkString = allLinks[i].outerHTML.toString();
		if (linkString.includes('lightcity-01.css')) {
			template = 'angelOfYahwehTEMPLATE-1'
		} else if (linkString.includes('lightcity-02.css')) {
			template = 'angelOfYahwehTEMPLATE-2'
		}
	}
	var saveText =
		`---
layout: ` + template + `
title: "` + pageTitle.innerHTML + `"
categories: [Angel of Yahweh]
---
    ` + document.querySelector('body').innerHTML +
		`</body>`;
	////////////////////////////////////////////////////////////////////////////////////////////
	//REMOVE THE MODIFICATION ADDED BY REFTAGGER BEFORE SAVING
	//This is useful for when you make a correction in a Bible reference or else it would still link to the old reference.
	saveText.toString();
	saveText = saveText.replace(/(>(\s|\n)+<)/g, "> <");
	saveText = saveText.replace(/<a[\s]*class="rtBibleRef"[\s]*([^>]*)>((?:(.|\n)(?!\<\/a\>))*(.|\n))<\/a>/g, "$2");
	//remove inline css generated by darkReader chrome plugin
	saveText = saveText.replace(/((((data-)*)|(--))*(darkreader)([^\s*]+)((\s\d*\w*)*)+(;|(?<!;)"))/g, "");
	//remove all inline styles
	// saveText = saveText.replace(/(style=\"[^\"]*\")/g, "");
	saveText = saveText.replace(/([\s]*class="H[\d]")/g, ""); //Remove H0 to H6 classes
	saveText = saveText.replace(/(cursor:[\s]*pointer;)/g, ""); //Remove sytle cursor: pointer
	saveText = saveText.replace(/(display:[\s]*none;)/g, ""); //Remove sytle display: none;
	saveText = saveText.replace(/([\s]*style="")/g, ""); //Remove empty sytle
	saveText = saveText.replace(/(<span>✦[\s]*<\/span>)/g, "");
	saveText = saveText.replace(/(<span>✧[\s]*<\/span>)/g, "");
	saveText = saveText.replace(/(contenteditable="false")/g, ""); //Remove contenteditable attribute
	saveText = saveText.replace(/(<script([^>]+)><\/script>)/g, ""); //Remove script elements
	saveText = saveText.replace(/(<nav([^>]+)>.*<\/nav>)/g, ""); //Remove nav bar
	////////////////////////////////////////////////////////////////////////////////////////////

	console.log(saveText);

	var fname = pageTitle.innerHTML;
	var filename = fname + `.html`;

	var blob = new Blob([saveText], {
		type: "text/plain;charset=utf-8"
	});
	saveAs(blob, filename);
}